services:
  ocis:
    image: owncloud/ocis:latest
    container_name: web
    entrypoint: /bin/sh
    command: ['-c', 'ocis init || true && ocis server']
    ports:
      - 9200:9200
    environment:
      OCIS_URL: https://localhost:9200
      OCIS_INSECURE: true
      OCIS_LOG_LEVEL: error
      IDM_ADMIN_PASSWORD: admin
      WEB_UI_CONFIG_FILE: /etc/ocis/web.json
      PROXY_ENABLE_BASIC_AUTH: true
    volumes:
      - ./dev/web.json:/etc/ocis/web.json:ro

  extension:
    image: nginx:1.25.3
    container_name: 3d_viewer
    ports:
      - 3000:80
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html:ro
